set -e
set -u

CIRCO_CLUSTER=${CIRCO_CLUSTER:-circotest1}
CIRCO_NAME=${CIRCO_NAME:-circo-0.1.1}
CIRCO_TAR=${CIRCO_TAR:-http://cbcrg-eu.s3.amazonaws.com/$CIRCO_NAME.tgz}
CIRCO_PORT=${CIRCO_PORT:-2551}
CIRCO_USER=${CIRCO_USER:-$USER}
CIRCO_HOME=${CIRCO_HOME:-$(eval echo ~${CIRCO_USER}/$CIRCO_NAME)}


echo CIRCO_HOME: $CIRCO_HOME 